src/main/resources/static/css/mainPage/mainPage.css, src/main/resources/static/js/mainPage/mainPage.js, src/main/resources/templates/mainPage/mainPid.html
=> mainPage html,css,js 만드는중입니다.

src/main/resources/mappers/temp-mapper.xml, src/main/resources/static/css/board/randomPeed.css, src/main/resources/static/css/header.css, src/main/resources/templates/board/randomPeed.html, src/main/resources/templates/fragments/header.html
=> glenBranch

src/main/java/edu/kh/cgram/member/controller/MemberController.java, src/main/java/edu/kh/cgram/member/mapper/MemberMapper.java, src/main/java/edu/kh/cgram/member/service/MemberService.java, src/main/java/edu/kh/cgram/member/service/MemberServiceImpl.java, src/main/java/edu/kh/cgram/member/util/HangulUtils.java, src/main/resources/application.properties, src/main/resources/mappers/member-mapper.xml, src/main/resources/static/css/header.css, src/main/resources/static/js/header.js, src/main/resources/templates/fragments/header.html
=> 사이드바 닉네임 이름 검색 기능 추가

src/main/java/edu/kh/cgram/myactivity/controller/MyActivityController.java, src/main/java/edu/kh/cgram/myactivity/mapper/MyActivityMapper.java, src/main/java/edu/kh/cgram/myactivity/service/MyActivityService.java, src/main/java/edu/kh/cgram/myactivity/service/MyActivityServiceImpl.java, src/main/resources/mappers/member-mapper.xml, src/main/resources/mappers/myactivity-mapper.xml, src/main/resources/static/css/board/myActivity.css, src/main/resources/static/css/header.css, src/main/resources/static/js/header.js, src/main/resources/templates/board/myActivity.html, src/main/resources/templates/fragments/header.html
사이드 바 기능 추가 및 내 활동 페이지 기능 추가 시작
=> 사이드 바 기능 추가 및 내 활동 페이지 기능 추가

src/main/java/edu/kh/cgram/board/dto/Board.java, src/main/java/edu/kh/cgram/board/dto/BoardImg.java, src/main/java/edu/kh/cgram/board/dto/Comment.java, src/main/java/edu/kh/cgram/main/controller/MainController.java, src/main/java/edu/kh/cgram/main/dto/Main.java, src/main/java/edu/kh/cgram/main/mapper/MainMapper.java, src/main/java/edu/kh/cgram/main/service/MainService.java, src/main/java/edu/kh/cgram/main/service/MainServiceImpl.java, src/main/java/edu/kh/cgram/member/dto/Member.java, src/main/resources/mappers/main-mapper.xml, src/main/resources/templates/peed/peedStory.html
=> mainPeed 백엔드 기본 세팅

src/main/java/edu/kh/cgram/chatting/controller/ChattingController.java, src/main/java/edu/kh/cgram/chatting/service/ChattingServiceImpl.java, src/main/resources/static/css/chatting/chatting.css, src/main/resources/static/js/chatting/chatting.js
=> 2024 11 20채팅 이미지 삽입 중

src/main/java/edu/kh/cgram/myactivity/controller/MyActivityController.java, src/main/java/edu/kh/cgram/myactivity/dto/CommentDetails.java, src/main/java/edu/kh/cgram/myactivity/mapper/MyActivityMapper.java, src/main/java/edu/kh/cgram/myactivity/service/MyActivityService.java, src/main/java/edu/kh/cgram/myactivity/service/MyActivityServiceImpl.java, src/main/resources/mappers/myactivity-mapper.xml, src/main/resources/static/css/board/myActivity.css, src/main/resources/static/js/board/myActivity.js, src/main/resources/templates/board/myActivity.html, src/main/resources/templates/fragments/header.html
=> 내활동 페이지 기능 마무리

src/main/java/edu/kh/cgram/board/dto/Board.java, src/main/java/edu/kh/cgram/main/controller/MainController.java, src/main/resources/static/css/peed/peedStory.css, src/main/resources/static/js/InfiniteScroll.js, src/main/resources/static/js/peed/mainPeed.js, src/main/resources/static/js/peed/mainPeedInfiniteScroll.js, src/main/resources/static/js/peed/peedStory.js, src/main/resources/templates/peed/mainPeed.html, src/main/resources/templates/peed/mainPeedOriginal.html
스토리 조회하는 백엔드 기능구현중.
무한 스크롤 mainPeed 에 적용중입니다.
=> 스토리 백엔드 , 무한스크롤 기능,

src/main/java/edu/kh/cgram/chatting/controller/ChattingController.java, src/main/java/edu/kh/cgram/chatting/dto/Message.java, src/main/java/edu/kh/cgram/chatting/service/ChattingService.java, src/main/java/edu/kh/cgram/chatting/service/ChattingServiceImpl.java, src/main/java/edu/kh/cgram/common/exception/FileUploadFailException.java, src/main/java/edu/kh/cgram/common/util/FileUtil.java, src/main/resources/static/css/chatting/chatting.css, src/main/resources/static/js/chatting/chatting.js, src/main/resources/templates/chatting/chatting.html
=> 2024 11 21  채팅 이미지 보내기 끝

src/main/resources/static/css/chatting/chatting.css, src/main/resources/static/js/chatting/chatting.js, src/main/resources/templates/chatting/chatting.html
=> chatting js 중복 수정

src/main/java/edu/kh/cgram/main/controller/MainController.java, src/main/resources/static/css/chatting/chatting.css, src/main/resources/static/js/chatting/chatting.js
=> 이미지 , 텍스트 같이 전송 1대1 채팅

src/main/java/edu/kh/cgram/main/controller/MainController.java, src/main/java/edu/kh/cgram/story/controller/StoryController.java, src/main/java/edu/kh/cgram/story/dto/Story.java, src/main/java/edu/kh/cgram/story/mapper/StoryMapper.java, src/main/java/edu/kh/cgram/story/service/StoryService.java, src/main/java/edu/kh/cgram/story/service/StoryServiceImpl.java, src/main/resources/mappers/story-mapper.xml, src/main/resources/static/css/feed/feedStory.css, src/main/resources/static/js/feed/feedStory.js, src/main/resources/templates/feed/feedStory.html, src/main/resources/templates/feed/mainFeed.html
스토리 조회, 
이미 본 스토리 뒤로 보내기 ( 정렬), 
24시간 내의 스토리만 불러오기
=> story 기본 세팅 및 메인피드에서 스토리 보는 방식 정리

src/main/java/edu/kh/cgram/main/controller/MainController.java
=> 에러 해결했습니다.

src/main/java/edu/kh/cgram/board/dto/Board.java, src/main/java/edu/kh/cgram/main/controller/MainController.java, src/main/java/edu/kh/cgram/story/controller/StoryController.java, src/main/java/edu/kh/cgram/story/mapper/StoryMapper.java, src/main/java/edu/kh/cgram/story/service/StoryService.java, src/main/java/edu/kh/cgram/story/service/StoryServiceImpl.java, src/main/resources/mappers/story-mapper.xml, src/main/resources/static/css/feed/memberRecommend.css, src/main/resources/static/js/feed/mainFeed.js, src/main/resources/static/js/feed/mainFeedInfiniteScroll.js, src/main/resources/templates/feed/mainFeed.html, src/main/resources/templates/fragments/memberRecommend.html
스토리 잘못 추가한 구문 주석(삭제) 처리 / mainFeed 좋아요기능 구현중
=> 스토리 잘못 추가한 구문 주석(삭제) 처리 / mainFeed 좋아요기능 구현중

src/main/java/edu/kh/cgram/board/controller/ApiBoardController.java, src/main/java/edu/kh/cgram/board/controller/BoardController.java, src/main/java/edu/kh/cgram/main/controller/MainController.java, src/main/java/edu/kh/cgram/main/mapper/MainMapper.java, src/main/java/edu/kh/cgram/main/service/MainService.java, src/main/java/edu/kh/cgram/main/service/MainServiceImpl.java, src/main/resources/mappers/board-mapper.xml, src/main/resources/mappers/main-mapper.xml, src/main/resources/static/js/feed/mainFeed.js, src/main/resources/static/js/feed/mainFeedInfiniteScroll.js, src/main/resources/templates/feed/mainFeed.html
mainFeed 에서 좋아요, keep 기능 구현 / 각종 값 조회-ing
=> mainFeed 에서 좋아요, keep 기능 구현 / 각종 값 조회-ing

src/main/java/edu/kh/cgram/chatting/controller/ChattingController.java, src/main/java/edu/kh/cgram/chatting/mapper/ChattingMapper.java, src/main/java/edu/kh/cgram/chatting/service/ChattingService.java, src/main/java/edu/kh/cgram/chatting/service/ChattingServiceImpl.java, src/main/resources/mappers/chatting.xml, src/main/resources/static/js/chatting/chatting.js, src/main/resources/templates/chatting/chatting.html
=> 2024 11 월 27 일 상대 프로필로 이동 가능

src/main/resources/static/css/chatting/chatting.css, src/main/resources/static/css/header.css, src/main/resources/static/js/chatting/chatting.js, src/main/resources/static/js/header.js
=> 2024 11 27

src/main/resources/static/js/myPage/myPage.js, src/main/resources/templates/myPage/myPage.html
=> 2024 11 월 27일 마이페이지 위치 조정

src/main/java/edu/kh/cgram/sse/controller/SseController.java, src/main/java/edu/kh/cgram/sse/mapper/SseMapper.java, src/main/java/edu/kh/cgram/sse/service/SseService.java, src/main/java/edu/kh/cgram/sse/service/SseServiceImpl.java, src/main/resources/mappers/sse-mapper.xml, src/main/resources/static/css/myPage/myPage-style.css, src/main/resources/static/js/myPage/myPage.js, src/main/resources/templates/fragments/header.html
2024 11 28 일 팔로우시 알림 ( 팔로우 버튼 미완성)
=> 2024 11 28 일 팔로우시 알림 ( 팔로우 버튼 미완성)

src/main/resources/static/js/myPage/myPage.js
=> 마이페이지 알림 요청 수정

src/main/java/edu/kh/cgram/board/dto/Board.java, src/main/java/edu/kh/cgram/board/dto/Recommend.java, src/main/java/edu/kh/cgram/main/controller/MainController.java, src/main/java/edu/kh/cgram/main/mapper/MainMapper.java, src/main/java/edu/kh/cgram/main/service/MainService.java, src/main/java/edu/kh/cgram/main/service/MainServiceImpl.java, src/main/resources/mappers/main-mapper.xml, src/main/resources/static/css/feed/mainFeed.css, src/main/resources/static/css/feed/memberRecommend.css, src/main/resources/static/js/feed/mainFeedInfiniteScroll.js, src/main/resources/static/js/feed/memberRecommend.js, src/main/resources/templates/feed/mainFeed.html, src/main/resources/templates/feed/mainFeedTest.html
=> mainFeed 업데이트 하는중입니다.

src/main/java/edu/kh/cgram/board/controller/BoardController.java, src/main/java/edu/kh/cgram/board/dto/Board.java, src/main/java/edu/kh/cgram/board/mapper/BoardMapper.java, src/main/java/edu/kh/cgram/board/service/BoardService.java, src/main/java/edu/kh/cgram/board/service/BoardServiceImpl.java, src/main/resources/mappers/board-mapper.xml, src/main/resources/static/js/feed/feedDetail.js, src/main/resources/templates/feed/feedDetail.html
=> 피드 상세 조회 페이지 수정 사항

src/main/java/edu/kh/cgram/admin/controller/AdminController.java, src/main/resources/mappers/sse-mapper.xml, src/main/resources/static/js/admin/admin-memberList.js, src/main/resources/static/js/chatting/chatting.js, src/main/resources/static/js/feed/mainFeed.js, src/main/resources/static/js/header.js, src/main/resources/templates/admin/admin-memberList.html, src/main/resources/templates/chatting/chatting.html
2024 12 02 어드민 페이지 신고관리 처리 시 회원 에게 알림, 알림 팔로우 완료
=> 2024 12 02 어드민 페이지 신고관리 처리 시 회원 에게 알림, 알림 팔로우 완료

src/main/resources/static/js/header.js
알림 팔로우 에서 팔로 우 시 상대방 회원 페이지도 팔로우 바낌
=> 알림 팔로우 에서 팔로 우 시 상대방 회원 페이지도 팔로우 바낌

src/main/resources/mappers/admin-mapper.xml, src/main/resources/static/css/chatting/chatting.css, src/main/resources/templates/chatting/chatting.html
=> 2024 12 02 채팅 회원 검색 중복 수정

src/main/java/edu/kh/cgram/report/controller/ReportController.java, src/main/java/edu/kh/cgram/report/mapper/ReportMapper.java, src/main/java/edu/kh/cgram/report/service/ReportService.java, src/main/java/edu/kh/cgram/report/service/ReportServiceImpl.java, src/main/resources/mappers/report-mapper.xml, src/main/resources/static/css/feed/feedModal(Do).css, src/main/resources/static/css/feed/mainFeed(Do).css, src/main/resources/static/css/feed/memberRecommend(Do).css, src/main/resources/static/js/feed/feedModal(Do).js, src/main/resources/static/js/feed/mainFeed.js, src/main/resources/templates/feed/feedMain(Do).html, src/main/resources/templates/feed/feedModal(Do).html
메인 피드 신고 기능 추가하였고 모달창 만들었습니다.(html에 붙이면 됨)
=> 메인 피드 신고 기능 추가하였고 모달창 만들었습니다.(html에 붙이면 됨)

src/main/resources/mappers/sse-mapper.xml, src/main/resources/static/css/feed/mainFeed(Do).css, src/main/resources/static/js/feed/feedDetail.js, src/main/resources/static/js/feed/mainFeed(Do).js, src/main/resources/templates/feed/feedMain(Do).html
=> 메인 피드 페이지 추천 팔로우 가능

src/main/resources/mappers/sse-mapper.xml, src/main/resources/static/js/feed/mainFeed(Do).js, src/main/resources/static/js/header.js, src/main/resources/templates/chatting/chatting.html
팔로우 회원 추천 목록 에서 회원 프로필 이동, 알림에서 읽음 목록 true ,false 로 알림창 빨간점 점등
=> 팔로우 회원 추천 목록 에서 회원 프로필 이동, 알림에서 읽음 목록 true ,false 로 알림창 빨간점 점등

src/main/resources/mappers/sse-mapper.xml, src/main/resources/static/css/feed/feedDetail.css, src/main/resources/static/js/feed/feedDetail.js, src/main/resources/static/js/header.js, src/main/resources/templates/feed/feedDetail.html
=>  피드 댓글의 좋아요 클릭시 알림

src/main/resources/mappers/main-mapper.xml, src/main/resources/static/css/feed/feedStory(Do).css, src/main/resources/static/js/feed/feedStory(Do).js, src/main/resources/static/js/feed/mainFeed(Do).js, src/main/resources/templates/feed/feedMain(Do).html
=> 무한스크롤 오류수정 및 무한스크롤 내용 업데이트

src/main/java/edu/kh/cgram/follow/controller/FollowController.java, src/main/java/edu/kh/cgram/follow/service/FollowService.java, src/main/resources/static/js/header.js, src/main/resources/static/js/myPage/myPage.js
알림 팔로 우 시 다시 상대방에게 팔로우 알림 보내짐 , 알림 이 왔을때 아이콘에 빨간 불 , 읽었을때 빨간불 사라짐
=> 알림 팔로 우 시 다시 상대방에게 팔로우 알림 보내짐 , 알림 이 왔을때 아이콘에 빨간 불 , 읽었을때 빨간불 사라짐

src/main/java/edu/kh/cgram/story/controller/StoryController.java, src/main/java/edu/kh/cgram/story/mapper/StoryMapper.java, src/main/java/edu/kh/cgram/story/service/StoryService.java, src/main/java/edu/kh/cgram/story/service/StoryServiceImpl.java, src/main/resources/mappers/main-mapper.xml
main에 잘못 병합된 데이터가 있어서 없애려고 커밋합니다
=> main에 잘못 병합된 데이터가 있어서 없애려고 커밋합니다

src/main/java/edu/kh/cgram/story/controller/StoryController.java, src/main/java/edu/kh/cgram/story/service/StoryService.java, src/main/java/edu/kh/cgram/story/service/StoryServiceImpl.java, src/main/resources/mappers/main-mapper.xml, src/main/resources/mappers/story-mapper.xml
=> main 변경되어서 재변경합니다.

src/main/java/edu/kh/cgram/story/controller/StoryController.java, src/main/java/edu/kh/cgram/story/mapper/StoryMapper.java, src/main/java/edu/kh/cgram/story/service/StoryService.java, src/main/java/edu/kh/cgram/story/service/StoryServiceImpl.java, src/main/resources/mappers/story-mapper.xml, src/main/resources/static/js/feed/feedStory(Do).js, src/main/resources/templates/feed/feedMain(Do).html
=> 스토리 기능구현했습니다

src/main/java/edu/kh/cgram/story/controller/StoryController.java
=> 에러 업데이트 했습니다

src/main/resources/mappers/story-mapper.xml
=> SQL 구문 오류 수정했습니다

src/main/resources/templates/feed/feedMain(Do).html
=> 회원 추천 목록 오류업데이트입니다

src/main/resources/static/css/feed/feedSlide(Do).css, src/main/resources/static/js/feed/feedStory(Do).js
=> 이미지 슬라이드 수정중입니다.

src/main/resources/static/js/feed/feedDetail.js
=> feedDetail.js 추가

src/main/resources/static/js/chatting/chatting.js
=> 채팅 방 마다의 상대방 프로필 사진
